[build]
  base = "/"
  command = "npm install && npm run build"
  functions = "build"
  publish = "/build/"

[functions]
  external_node_modules = ["express"]
#  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
